export const URL_TEN_AGENT = 'https://agent.theten.ai'
export const BLOG = '/blog'
export const URL_TEN_FRAMEWORK_DOC = '/docs/ten_framework/concept_overview'
export const HUGGING_FACE_SPACE = 'https://huggingface.co/TEN-framework'
export const URL_TEN_TURN_DETECTION = 'https://github.com/ten-framework/ten-turn-detection'
