// Sample project data for the ProjectsShowcase component
export const SAMPLE_PROJECTS = [
	{
		id: 1,
		title: 'TEN Agent Voice Assistant',
		description: 'Real-time multimodal AI agent with voice capabilities',
		category: 'AI Agent',
		author: 'TEN Team',
		remixes: '2.1k',
		image: '/api/placeholder/300/200',
		href: '#',
	},
	{
		id: 2,
		title: 'Real-time Translation Bot',
		description: 'Multi-language translation with voice synthesis',
		category: 'Translation',
		author: 'Community',
		remixes: '1.8k',
		image: '/api/placeholder/300/200',
		href: '#',
	},
	{
		id: 3,
		title: 'Smart Meeting Assistant',
		description: 'AI-powered meeting transcription and summarization',
		category: 'Productivity',
		author: 'DevTeam',
		remixes: '1.5k',
		image: '/api/placeholder/300/200',
		href: '#',
	},
	{
		id: 4,
		title: 'Interactive Storyteller',
		description: 'AI that creates and narrates interactive stories',
		category: 'Entertainment',
		author: 'StoryAI',
		remixes: '2.3k',
		image: '/api/placeholder/300/200',
		href: '#',
	},
	{
		id: 5,
		title: 'Code Review Assistant',
		description: 'AI-powered code analysis and suggestions',
		category: 'Developer Tools',
		author: 'CodeBot',
		remixes: '1.9k',
		image: '/api/placeholder/300/200',
		href: '#',
	},
	{
		id: 6,
		title: 'Health Monitoring Agent',
		description: 'Personal health assistant with voice interaction',
		category: 'Healthcare',
		author: 'HealthTech',
		remixes: '1.2k',
		image: '/api/placeholder/300/200',
		href: '#',
	},
]
