name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun downloads
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Cache Next build cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-

      - name: Install dependencies
        run: bun install --no-progress

      - name: Typecheck
        run: bun run typecheck

      - name: Lint (Biome)
        run: bun run lint

      - name: Build
        run: bun run build
